---
- name: Install iptables-persistent package
  apt: name="iptables-persistent" state="present"

- name: Install iptables ipv4 file
  template:
    src: rules.v4.j2
    dest: /etc/iptables/rules.v4
  notify: reload iptables

- name: Install iptables ipv6 file
  template:
    src: rules.v6.j2
    dest: /etc/iptables/rules.v6
  notify: reload iptables

- name: Flush handlers
  meta: flush_handlers
