---
- name: Install base packages
  apt:
    name: "{{ item }}"
    state: "present"
    update_cache: yes
    cache_valid_time: "3600"
  with_items:
    - "ca-certificates"
    - "zip"
    - "unzip"
    - "git"
    - "tar"
    - "python-lxml"
    - "parted"
    - "less"
    - "curl"
